version: '2'
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
      MYAPP_DB_USER: root
      MYAPP_DB_PASSWORD: $MYAPP_DB_PASSWORD
      MYAPP_DB_HOST: mysql
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/DartsHoo
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: $MYAPP_DB_PASSWORD
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
